import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillTwitterCircle, AiFillGithub } from 'react-icons/ai';
import Image from "next/image";
import gelyace from '../public/gel-notion.svg';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/orderly2.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.svg';
import web4 from '../public/web1.svg';
import web5 from '../public/Home.svg';
import web6 from '../public/hatchitlol.png';



export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Angelica Zaragoza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-black md:px-20 lg:px-40">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className=" text-xl font-mono" >gelzaragoza</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-black text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1geGdi2LsdG-MwBbhGUT7yf6oifB_Y-gX/view?usp=sharing" 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  download="AngelicaResume.pdf" 
                >
                  Download Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <div className="relative bg-black rounded-full mx-auto w-80 h-80 mb-10 overflow-hidden md:h-96 md:w-96">
              <Image
                src={gelyace}
                layout="fill"
                objectFit="cover"
                alt="Angelica Zaragoza Portrait"
              />
            </div>
            <h2 className=" text-5xl py-2 dark:text-white font-medium md:text-6xl">Angelica Zaragoza</h2>
            <h3 className=" text-2xl text-rose-600 py-2 md:text-3xl">
              Frontend Designer{" "}
              <span role="img" aria-label="wave">
                👋
              </span>
            </h3>
            <p className=" text-md py-5 leading-8 dark:text-white md:text-xl max-w-xl mx-auto">
              Hello world! I&lsquo;m Gel, a passionate Frontend Developer and UX Designer who aspires to continously learn software and design tools &apos;
              in order to make the web more usable one page at a time.
              <p className="py-5">Dive into my tech journey below! </p>
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 dark:text-rose-600">
            <a href="https://twitter.com/gelzaragoza" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/angelica-zaragoza/" target="_blank">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/gelzaragoza" target="_blank">
              <AiFillGithub />
            </a>
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-rose-500 text-3xl py-1 pt-5">Services I Offer</h3>
            <p className=" text-lg py-2 leading-8  dark:text-white">
              Throughout my journey in the tech industry, I have honed the skills to provide professional services for agencies and startups that encompass compelling design, seamless web development, and effective digital marketing. I specialize in crafting visually appealing designs, developing user-friendly websites, and curating engaging content for social media platforms.
            </p>
          </div>
          <div className="lg:flex gap-10 py-20">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <div className="flex justify-center">
                <Image
                  src={design}
                  width={100}
                  height={100}
                  alt="Design Image Description"
                />
              </div>
              <h3 className=" dark:text-rose-600 text-2xl font-semibold pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating seamless and elegant designs suited for your needs following core
                design theory.
              </p>
              <div className="flex flex-wrap gap-4 dark:text-white text-rose-600 py-2 justify-center">
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Figma</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Photoshop</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Illustrator</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Canva</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">WebFlow</h4>
                </div>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex justify-center">
                <Image
                  src={code}
                  width={100}
                  height={100}
                  alt="Code Image Description"
                />
              </div>
              <h3 className=" dark:text-rose-600 text-2xl font-semibold pt-8 pb-2  ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&lsquo;s make it a
                reality.
              </p>
              <div className="flex flex-wrap gap-4 dark:text-white text-rose-600 py-2 justify-center">
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">React</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">NextJS</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Tailwind</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Javascript</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">HTML/CSS</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">MongoDB</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">NodeJS</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">MUI</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Git</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Azure DevOps</h4>
                </div>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex justify-center">
                <Image
                  src={consulting}
                  width={100}
                  height={100}
                  alt="Consulting Image Description"
                />
              </div>
              <h3 className=" dark:text-rose-600 text-2xl font-semibold pt-8 pb-2  ">
                Marketing
              </h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <div className="flex flex-wrap gap-4 dark:text-white text-rose-600 py-2 justify-center">
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Meta Business Suite</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Hubspot</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Buffer</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Adobe Creative Cloud</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">Google Apps for Business</h4>
                </div>
                <div className="dark:bg-white rounded-md p-2 shadow-md">
                  <h4 className="text-lg font-mono dark:text-rose-600">TweetDeck</h4>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-rose-500 text-3xl py-1 pt-5">Portfolio</h3>
            <p className=" text-lg py-2 leading-8  dark:text-white">
              Welcome to my digital gallery, where creativity meets innovation. Explore a curated collection of my finest work, showcasing the blend of design and technology that fuels my passion. Each project is a testament to my dedication to creating seamless user experiences and visually stunning designs. Join me on this visual journey through my portfolio – a testament to my love for design and technology!            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg">
                <Image
                  width={100}
                  height={100}
                  layout="responsive"
                  src={web1}
                  alt="Project 1 Description"
                />
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg">
                <Image
                  width={100}
                  height={100}
                  layout="responsive"
                  src={web2}
                  alt="Project 2 Description"
                />
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg">
                <Image
                  width={100}
                  height={100}
                  layout="responsive"
                  src={web3}
                  alt="Project 3 Description"
                />
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg">
                <Image
                  width={100}
                  height={100}
                  layout="responsive"
                  src={web4}
                  alt="Project 4 Description"
                />
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg">
                <Image
                  width={100}
                  height={100}
                  layout="responsive"
                  src={web5}
                  alt="Project 5 Description"
                />
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg">
                <Image
                  width={100}
                  height={100}
                  layout="responsive"
                  src={web6}
                  alt="Project 6 Description"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
